package com.web.generator.model;

import io.jboot.db.annotation.Table;
import com.web.generator.model.base.BaseSysUser;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sys_user", primaryKey = "id")
public class SysUser extends BaseSysUser<SysUser> {

}
